name: Test Deploy

on:
  push:
    branches: ["dev", "dev", "actionsBranch"]
  pull_request:
    branches: ["main", "dev", "actionsBranch"]

jobs:
  cypress_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install && npm ci
      - name: Start the client server
        run: nohup cd ./client && npm run dev
      - name: Start the dotnet server
        run: nohup cd .. && cd ./server && dotnet run
      - name: Install Cypress dependencies
        run: cd ./cypress && npm ci
      - name: Run cypress
        run: npm run test

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Doing a deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/Auction_site
            git pull
            ~~~~
